name: BuildTestDeploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  BUILD_TYPE: Release

jobs:
  linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Checkout submodules
      run: git submodule update --init --recursive
    
    - name: Install python and boost
      run: sudo apt-get install python3.8 python3.8-dev libboost-python-dev

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Install
      run: cmake --install ${{github.workspace}}/build --prefix ${{github.workspace}}/install
      
    - name: Test
      working-directory: ${{github.workspace}}/install
      run: test/smoke_tests.py
      
    - name: Package
      working-directory: ${{github.workspace}}/install
      run: tar -zcvf ${{github.workspace}}/namigator.tar.gz .

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: namigator.tar.gz
        path: namigator.tar.gz
        retention-days: 5

  windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Checkout submodules
      run: git submodule update --init --recursive
    
    - name: Install python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
        architecture: 'x64'

    - name: Build Boost
      run: |
        Invoke-WebRequest https://boostorg.jfrog.io/artifactory/main/release/1.78.0/source/boost_1_78_0.zip -OutFile boost.zip
        Expand-Archive -Path boost.zip -DestinationPath .
        cd boost_1_78_0
        .\bootstrap
        .\b2 --with-python link=static threading=multi runtime-link=shared architecture=x86 address-model=64 stage

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DBOOST_ROOT=${{github.workspace}}/boost_1_78_0 -DBOOST_LIBRARYDIR=${{github.workspace}}/boost_1_78_0/stage/lib

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Install
      run: cmake --install ${{github.workspace}}/build --prefix ${{github.workspace}}/install
      
    - name: Test
      working-directory: ${{github.workspace}}/install
      run: python test/smoke_tests.py
      continue-on-error: true
      
    - name: Package
      run: Compress-Archive -Path install\* -DestinationPath namigator.zip

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: snapshot-devbuild
        path: namigator.zip
        retention-days: 2

    - name: Download artifact snapshot
      uses: actions/download-artifact@v1
      with:
        name: snapshot-devbuild
        path: all_snapshots

    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

    - name: Upload snapshot
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: true
        title: "Development Build(${{ steps.date.outputs.date }})"
        files: all_snapshots
